name: Compilability check
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        abi: [ "armeabi-v7a", "arm64-v8a", "x86", "x86_64" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Setup the environment
        run: |
          sudo pip3 install meson==0.58.2
          sudo apt-get install nasm ninja-build

      - name: What Cmake binary do we have?
        run: ls $ANDROID_HOME/cmake/3.10.2.4988404/bin

      - name: Executing the script
        run: ./ffmpeg-android-maker.sh -all-free -all-gpl -android=18 -abis=${{ matrix.abi }}
        env:
          ANDROID_SDK_HOME: $ANDROID_HOME
          ANDROID_NDK_HOME: $ANDROID_NDK_LATEST_HOME
